Models/Add_item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lubricants.Models
{
    public class Add_item
    {
        public List<Item_category> item_Categories { set; get; }


        [Key]
        public int id { get; set; }

        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Select category", Prompt = "Category")]
        public int Category_id { get; set; }

        [Display(Name = "Item name:", Prompt = "Item name")]
        [Required]
        [MaxLength(50)]
        public string Item_name { get; set; }

        [Display(Name = "Item price:", Prompt = "Price in Ksh.")]
        [DataType(DataType.Currency)]
        [Required]
        public float Item_price { get; set; }

        [Display(Name = "Item quantity:", Prompt = "Quantity")]
        [Required]
        public int Quantity { get; set; }
        

        [Required]
        //[DataType(DataType.Date)]
        public string DateTime { get; set; }

        [ForeignKey("IDT")]
        public Item_category category { get; set; }


    }
}

Controllers/Add_itemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fuela.DBContext;
using Lubricants.Models;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Http;
using Microsoft.CodeAnalysis;

namespace Lubricants.Controllers
{
    public class Add_itemController : Controller
    {
        private readonly ApplicationDBContext _context;
        static Boolean search;

        public Add_itemController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Add_item
        public IActionResult Index()
        {

            return View();

        }

        public IActionResult Reports()
        {

            string currentDate = DateTime.Now.ToString("yyyy-MM-dd");
            //ViewBag.d = currentDate;
            List<Add_item> ListOfItems = _context.Add_item.ToList();
            List<Item_category> categorys = _context.Items_category.ToList();
            //List<JoinCategoryAndItem> joinList = new List<JoinCategoryAndItem>();
            List<Stock_summary> joinList = new List<Stock_summary>();
            List<Submited_stock> Submitted = _context.Submited_stock.ToList();

            var results = (from pd in categorys
                           join od in ListOfItems on pd.IDT equals od.Category_id
                           join sd in Submitted on od.id equals sd.item_id 
                           select new
                           {
                               pd.Category_name,
                               od.Item_price,
                               pd.ImageURL,
                               od.Item_name,
                               od.Quantity,
                               od.id,
                               sd.Cash_made,
                               sd.item_sold,
                               sd.User_id,

                           }).ToList();

            foreach (var item in results)
            {
                Stock_summary JoinObject = new Stock_summary();
                JoinObject.Category_name = item.Category_name;
                JoinObject.Item_price = item.Item_price;
                JoinObject.ImageURL = item.ImageURL;
                JoinObject.Quantity = item.Quantity;
                JoinObject.Item_name = item.Item_name;
                JoinObject.id = item.id;
                JoinObject.item_sold = item.item_sold;
                JoinObject.Cash_made = item.Cash_made;
                JoinObject.User_id = item.User_id;
                joinList.Add(JoinObject);
                var JoinListToViewbag = joinList.ToList();
                ViewBag.JoinList = JoinListToViewbag;

            }
            return View();
        }

       

    

        public void ConfirmStockSubmit(int id, int Quantity, String Item_name)
        {
            var query = _context.Add_item.Where(x => x.id == id).Single();
            ViewBag.InitialQuantity = query.Quantity;
            ViewBag.CurrentQuantity = Quantity;
            ViewBag.price = Quantity;
            float price = query.Item_price;
            int sold = int.Parse(query.Quantity.ToString()) - Quantity;
            float cashMade = price * sold;
            ViewBag.ChashMade = cashMade;
            //ViewBag.EnteredQuantity = Item_name;



        }
        public void bindSubmitItems()
        {
            string currentDate = DateTime.Now.ToString("yyyy-MM-dd");
            //ViewBag.d = currentDate;
            List<Add_item> ListOfItems = _context.Add_item.ToList();
            List<Item_category> categorys = _context.Items_category.ToList();
            List<JoinCategoryAndItem> joinList = new List<JoinCategoryAndItem>();

            var results = (from pd in categorys
                           join od in ListOfItems on pd.IDT equals od.Category_id
                           where od.DateTime != currentDate && od.Quantity > 0
                           select new
                           {
                               pd.Category_name,
                               od.Item_price,
                               pd.ImageURL,
                               od.Item_name,
                               od.Quantity,
                               od.id,

                           }).ToList();

            foreach (var item in results)
            {
                JoinCategoryAndItem JoinObject = new JoinCategoryAndItem();
                JoinObject.Category_name = item.Category_name;
                JoinObject.Item_price = item.Item_price;
                JoinObject.ImageURL = item.ImageURL;
                JoinObject.Quantity = item.Quantity;
                JoinObject.Item_name = item.Item_name;
                JoinObject.id = item.id;
                joinList.Add(JoinObject);


                var JoinListToViewbag = joinList.ToList();
                ViewData["SearchStatus"] = search;

                ViewBag.JoinList = JoinListToViewbag;

            }
        }
        public IActionResult SubmitStock()
        {
            bindSubmitItems();
            ViewBag.AllowPopup = "2";

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitStock(int id, int Quantity, [Optional] string newItem)
        {

            var query = _context.Add_item.Where(x => x.id == id).Single();
            ViewBag.InitialQuantity = query.Quantity;
            ViewBag.CurrentQuantity = Quantity;
            float price = query.Item_price;
            int sold = int.Parse(query.Quantity.ToString()) - Quantity;
            float cashMade = price * sold;
            ViewBag.ChashMade = cashMade;
            ViewBag.price = price;
            ViewBag.Item_name = query.Item_name;

            ViewBag.sold = sold;
            ViewBag.id = id;
            ViewBag.EnteredQuantity = Quantity;

            ViewBag.AllowPopup = "1";
            bindSubmitItems();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitStockPost(int id, int Quantity, [Optional] string newItem)
        {
            int closing_stock = Quantity;
            //var combineList = _context.Add_item.Where(x => x.id == id);
            var allFields = await _context.Add_item.FindAsync(id);
            int database_stock = allFields.Quantity;
            int itemSold = database_stock - closing_stock;
            int newQuantity = Quantity;

            if(itemSold<0){
                TempData["StockUpdateStatus1"] = "Submitted closing  stock value for " + allFields.Item_name + " is incorrect.";
            }
            else
            {
                AddSession(itemSold.ToString(), itemSold.ToString());
                var query = _context.Add_item.Where(x => x.id == id).Single();
                //LETS UPDATE VALUES IN DATABASE
                query.Quantity = newQuantity;
                query.DateTime = DateTime.Now.ToString("yyyy-MM-dd");
                _context.Update(query);
                await _context.SaveChangesAsync();


                //LETS CALCULATE CASH MADE

                float price = query.Item_price;
                float cashMade = price * itemSold;
                Guid g = Guid.NewGuid();
                //LETS ADD SUBMITTED STOCK TO THEIR RESPECTIVE TABLES
                var submitted = new Submited_stock()
                {
                    item_id = id,
                    DateTime = DateTime.Now.ToString("yyyy-MM-dd"),
                    item_sold = itemSold,
                    Cash_made = cashMade,
                    User_id = g.ToString()

                };
                _context.Add(submitted);
                _context.SaveChanges();
                TempData["StockUpdateStatus"] = query.Item_name + " has been submitted successfully! \n Initial stock: " + database_stock + "\n Item sold: " + itemSold + "\n New stock: " + Quantity;
                bindSubmitItems();

            }


            return RedirectToAction(nameof(SubmitStock));

        }
        public void AddSession(string SessionName, string SessionData)
        {
            HttpContext.Session.SetString(SessionName, SessionData.ToString());
        }
        // GET: Add_item/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var add_item = await _context.Add_item
                .FirstOrDefaultAsync(m => m.Category_id.ToString() == id);
            if (add_item == null)
            {
                return NotFound();
            }

            return View(add_item);
        }

        // GET: Add_item/Create
        public void BindCategoryName()
        {
            //string selectedValue = cateGory.Category_name;
            List<Item_category> CategoryList = new List<Models.Item_category>();
            CategoryList = (from items in _context.Items_category select items).ToList();
            //idList.Insert(0, new Rental_Owners { National_id=0,Full_names})
            CategoryList.Insert(0, new Item_category { IDT = 0, Category_name = "--Select Category--" });
            ViewBag.categoryList = CategoryList;
        }
        public IActionResult Create(Item_category cateGory, [Optional] string Value)
        {

            var combineList = _context.Add_item.ToList();
            ViewBag.itemlist = combineList;
            List<Add_item> ListOfItems = _context.Add_item.ToList();
            List<Item_category> categorys = _context.Items_category.ToList();
            List<JoinCategoryAndItem> joinList = new List<JoinCategoryAndItem>();

            var results = (from pd in categorys
                           join od in ListOfItems on pd.IDT equals od.Category_id
                           select new
                           {

Controllers/Item_categoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fuela.DBContext;
using Lubricants.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Grpc.Core;
using Microsoft.AspNetCore.Authorization;

namespace Lubricants.Controllers
{
    public class Item_categoryController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public Item_categoryController(ApplicationDBContext context,IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Item_category
    
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items_category.ToListAsync());
        }

       

        // GET: Item_category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item_category = await _context.Items_category
                .FirstOrDefaultAsync(m => m.IDT == id);
            if (item_category == null)
            {
                return NotFound();
            }

            return View(item_category);
        }
        //acha nkuekee ya kulog uot...so kwanza tunadisplayub user ...but unaezaweka invisible..
        // GET: Item_category/Create
        [Authorize]
        public IActionResult Create()
        {
            List<Item_category> itemlist = _context.Items_category.ToList();
            ViewBag.itemlist = itemlist;
            return View();
        }
        //run
        // POST: Item_category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Item_category model)
        {
            string fileName = System.IO.Path.GetFileName(model.Category_image.FileName);
            string filePath = "/Images/" + fileName;

            if (ModelState.IsValid)
            {
                if (model.Category_image !=null)
                {
                    string folder = "images/"+Guid.NewGuid().ToString() + model.Category_image.FileName;
                    folder += Guid.NewGuid().ToString() + model.Category_image.FileName;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);
                    await model.Category_image.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

                    //model.SaveAs(Server.MapPath(filePath));

                    //var filename = Path.GetFileName(file.FileName);
                    //var path = Path.Combine(Server.MapPath("~/Uploads/Photo/"), filename);
                    //file.SaveAs(path);
                    //tyre.Url = filename;


                    Item_category itemC = new Item_category
                    {
                        Category_name = model.Category_name,
                        ImageURL = folder,
                     
                    };
                    _context.Add(itemC);
                    await _context.SaveChangesAsync();
                }

               
            }

            List<Item_category> itemlist = _context.Items_category.ToList();
            ViewBag.itemlist = itemlist;
            return RedirectToAction(nameof(Create));

            //return View(await _context.Items_category.ToListAsync());


        }


        // GET: Item_category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item_category = await _context.Items_category.FindAsync(id);
            if (item_category == null)
            {
                return NotFound();
            }
            return View(item_category);
        }

        // POST: Item_category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Category_title")] Item_category item_category)
        {
            if (id != item_category.IDT)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item_category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Item_categoryExists(item_category.IDT))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item_category);
        }

        // GET: Item_category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item_category = await _context.Items_category
                .FirstOrDefaultAsync(m => m.IDT == id);
            if (item_category == null)
            {
                return NotFound();
            }

            return View(item_category);
        }

        // POST: Item_category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item_category = await _context.Items_category.FindAsync(id);
            _context.Items_category.Remove(item_category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Item_categoryExists(int id)
        {
            return _context.Items_category.Any(e => e.IDT == id);
        }
    }
}

Views/Add_item/Add_stock.cshtml
@model Lubricants.Models.Add_item

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card card-1">
    <div class="card-body">
        <h4><img src="/SystemImage/addcategory.png" class="logo1" alt="" /> &nbsp;Add new stock&nbsp;| &nbsp;@ViewBag.itemName </h4>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="card card-1">

            <div class="card-body">
                <form asp-action="Add_stock" class="text-center">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Category_id" />
                    <div class="form-group">
                        @*<label asp-for="Item_name" class="control-label"></label>*@
                        <input type="hidden" asp-for="Item_name" class="form-control" />
                        <span asp-validation-for="Item_name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*<label asp-for="Item_price" class="control-label"></label>*@
                        <input type="hidden" asp-for="Item_price" class="form-control" />
                        <span asp-validation-for="Item_price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label" ></label>
                        <input asp-for="Quantity"  value="" class="form-control customeInput1" style="padding:20px;" placeholder="Enter new ammount that was added"/>
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*<label asp-for="DateTime" class="control-label"></label>*@
                        <input type="hidden" asp-for="DateTime" class="form-control" />
                        <span asp-validation-for="DateTime" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <Button type="submit" class="btn btn-primary"> Submit &nbsp;<i class="fa fa-cloud-upload" aria-hidden="true"></i></Button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-12" style="margin-top:10px;">
        @*<div class="card card-1">

            <div class="card-body">*@
                @if (ViewBag.NewQuantity != null)
                {
                    <div class="alert alert-primary" role="alert">
                       <table class="table">
                           <tr><td colspan="2"><strong>Success!</strong> &nbsp; New items have been recorded </td></tr>
                           <tr>
                               <td>Initial quantity:</td><td>@ViewBag.InitialQuantity</td>
                           </tr>
                           <tr>
                               <td>New quantity:</td><td>@ViewBag.NewQuantity</td>
                           </tr>
                       </table>
                    </div>
                }
            @*</div>
            </div>*@

            </div>

            <div>
                @*<a asp-action="Index">Back to List</a>*@
            </div>

            @section Scripts {
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
            }

Views/Add_item/Create.cshtml
@model Lubricants.Models.Add_item

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*<h1>Item details</h1>*@
<div class="card card-1 bg-light text-dark">
    <div class="card-body ">
        <div class="row">
            <div class="col-lg-12">


                <h4>
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> &nbsp;Availlable items

                </h4>
            </div>
           
        </div>
    </div>
</div>
<br />
@*<hr />*@
<div class="row">
    <div class="col-md-4">
        <div class="card card-1 bg-light " style="border:none">
            <div class="card-header text-left bg-custome text-light " style="        background-color: #1ABC9C
">
                <i class="fa fa-plus-circle" aria-hidden="true"></i> &nbsp; Add new items
            </div>
            <div class="card-body text-dark">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Category_id" class="control-label"></label>
                        <select asp-for="Category_id" class="form-control"
                                asp-items="@(new SelectList(@ViewBag.categoryList, "IDT", "Category_name"))">
                        </select>



                        @*<input asp-for="Department" class="form-control" />*@
                        @*<span asp-validation-for="Department" class="text-danger"></span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="Item_name" class="control-label"></label>
                        <input asp-for="Item_name" class="form-control" />
                        <span asp-validation-for="Item_name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Item_price" class="control-label"></label>
                        <input asp-for="Item_price" class="form-control" />
                        <span asp-validation-for="Item_price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateTime" class="control-label"></label>
                        <input asp-for="DateTime" class="form-control" />
                        <span asp-validation-for="DateTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Submit &nbsp;  <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                        </button>
                        <a  class="btn btn-primary" asp-action="Create" asp-controller="Item_category">
                            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;  Add new category 
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="card card-1 " style="margin-bottom:10px;margin-top:10px;border:none;">

            <div class="card-header text-left bg-light">
                <div class="col-lg-12" style="margin-top:10px;">
                    @using (Html.BeginForm("Create", "Add_item", FormMethod.Get))
                    {

                        <div class="input-group mb-3">
                            <input class="form-control my-0 py-1 red-border" type="text" name="Value" value="@ViewBag.SearchValue" required placeholder="Search for items" aria-label="Search">
                            <div class="input-group-append">

                                <button type="submit" class="btn btn-dark">Search &nbsp;<i class="fa fa-search" aria-hidden="true"></i></button>


                            </div>
                        </div>
                    }
                </div>

            </div>
            </div>

                @if (ViewBag.ItemsCount != null)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Items found </strong><h1 class="badge badge-pill badge-secondary">
                            @ViewBag.ItemsCount
                        </h1>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                }

                @{
                    if (ViewBag.JoinList != null)
                    {
                        @foreach (var item in ViewBag.JoinList)
                        {
                            <div class="card card-1 " style="margin-bottom:10px;margin-top:10px;border:none;">

                                <div class="card-header text-left bg-dark text-light">
                                    <img src="/@item.ImageURL" alt="" class="rounded-circle" style="height:50px;width:50px;border:2px white solid" /> &nbsp;&nbsp;  @item.Category_name
                                </div>
                                <div class="card-body text-light">
                                    <table class="table table-light table-striped ">

                                        <tr>
                                            <td><i class="fa fa-shopping-cart" aria-hidden="true"></i> &nbsp;  Item name</td>
                                            <td>
                                                <span class="badge badge-pill badge-dark">@item.Item_name</span> 
                                            </td>
                                        </tr>
                                        @*<tr>
                                            <td><i class="fa fa-circle" aria-hidden="true"></i> &nbsp; Item category</td>

                                            <td>
                                                @item.Category_name

                                            </td>
                                        </tr>*@
                                        <tr>

                                            <td><i class="fa fa-suitcase" aria-hidden="true"></i> &nbsp;Current Quantity</td>


                                            <td>
                                                <span class="badge badge-pill badge-dark"> @item.Quantity</span>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-usd" aria-hidden="true"></i> &nbsp;Item price</td>

                                            <td>
                                                <span class="badge badge-pill badge-dark">  Ksh.&nbsp; @item.Item_price</span>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <div class="btn-group-sm" role="group" aria-label="First group">
                                                    <a class="btn btn-dark text-light" asp-action="Edit" asp-controller="Add_item" asp-route-id="@item.id"><i class="fa fa-usd" aria-hidden="true"></i>&nbsp;Change price</a>
                                                    <a class="btn btn-dark text-light" asp-action="Add_stock" asp-controller="Add_item" asp-route-id=" @item.id"><i class="fa fa-cart-plus" aria-hidden="true"></i>&nbsp;Restock</a>


                                                </div>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td colspan="2">
                                                <div class="btn-group-sm" role="group" aria-label="First group">

                                                    <a class="btn btn-primary text-light" asp-action="Delete" asp-controller="Add_item" asp-route-id="3"><i class="fa fa-trash" aria-hidden="true"></i>&nbsp;Remove</a>
                                                   

                                                </div>
                                            </td>
                                        </tr>

                                    </table>

                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="alert alert-danger" role="alert" style="margin-top:10px;">
                            <h4 class="alert-heading">No items found</h4>
                            <p>No items found please check the item name and try again!</p>
                            <hr>
                            <p class="mb-0">NB:If you cannot find item by name you can search the item by their category names.</p>
                        </div>

                    } }
            </div>
        </div>


        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }