Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Lubricants.Models;
using Fuela.DBContext;
using Microsoft.AspNetCore.Http;

namespace Lubricants.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDBContext _context;
      
        public HomeController(ApplicationDBContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;

        }
        private readonly ILogger<HomeController> _logger;

       

        public IActionResult LoginUser(c_Users user)
        {
            if (user.strUserId == null || user.strPassword == null)
            {
                return Content("put user/pass");
            }
            var Username = user.strEmail;

            TokenProvider TokenProvider = new TokenProvider(_context);

            var userToken = TokenProvider.LoginUser(user.strUserId, user.strPassword);
            if (userToken == null)
            {

                return Content("Incorrect User Or Pass");

            }

            HttpContext.Session.SetString("JWToken", userToken);
            HttpContext.Session.SetString("User", Username);
            return Redirect("~/Administration/Dashboard");

        }
        public IActionResult Logoff()
        {
            HttpContext.Session.Clear();
            return Redirect("~/Home/Index");

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/c_UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fuela.DBContext;
using Lubricants.Models;

namespace Lubricants.Controllers
{
    public class c_UsersController : Controller
    {
        private readonly ApplicationDBContext _context;

        public c_UsersController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: c_Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.c_Users.ToListAsync());
        }

        // GET: c_Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var c_Users = await _context.c_Users
                .FirstOrDefaultAsync(m => m.strUserId == id);
            if (c_Users == null)
            {
                return NotFound();
            }

            return View(c_Users);
        }

        // GET: c_Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: c_Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("strPhone,strDOB,strEmail,strPassword,strUserId,strRole")] c_Users c_Users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(c_Users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(c_Users);
        }

        // GET: c_Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var c_Users = await _context.c_Users.FindAsync(id);
            if (c_Users == null)
            {
                return NotFound();
            }
            return View(c_Users);
        }

        // POST: c_Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("strPhone,strDOB,strEmail,strPassword,strUserId,strRole")] c_Users c_Users)
        {
            if (id != c_Users.strUserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(c_Users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!c_UsersExists(c_Users.strUserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(c_Users);
        }

        // GET: c_Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var c_Users = await _context.c_Users
                .FirstOrDefaultAsync(m => m.strUserId == id);
            if (c_Users == null)
            {
                return NotFound();
            }

            return View(c_Users);
        }

        // POST: c_Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var c_Users = await _context.c_Users.FindAsync(id);
            _context.c_Users.Remove(c_Users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool c_UsersExists(string id)
        {
            return _context.c_Users.Any(e => e.strUserId == id);
        }
    }
}

Views/Home/Index.cshtml
@model Lubricants.Models.c_Users
@{
    ViewData["Title"] = "Home Page";
}
<div style="margin-top:20px;">
  
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                @using (Html.BeginForm("LoginUser", "Home", FormMethod.Post, new { role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                        <div class="card-body">
                                            <form>
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                    @Html.TextBoxFor(m => m.strUserId, new { @class = "form-control py-4", @placeholder = "Email" })
                                                </div>
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputPassword">Password</label>
                                                    @Html.PasswordFor(m => m.strPassword, new { @class = "form-control py-4", @placeholder = "Password" })
                                                </div>
                                                <div class="form-group">
                                                    <div class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" id="rememberPasswordCheck" type="checkbox" />
                                                        <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                                    </div>
                                                </div>
                                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                    <a class="small" href="password.html">Forgot Password?</a>
                                                    <button type="submit" class="btn btn-primary" href="index.html">Login</button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="card-footer text-center">
                                            <div class="small"></div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
       
 

    <div class="row">
        <div class=" col-lg-4 col-md-4 col-sm-4  "></div>

        <div style="margin-top:24px;margin-left:16px;margin-right:16px; padding:16px;" class=" col-lg-4 col-md-4 col-sm-4 thumbnail ;box-shadow:0 4px 8px rgba(1,1,0.2,0.2)">
            @using (Html.BeginForm("LoginUser", "Home", FormMethod.Post, new { role = "form" }))
            {
                <div style="margin-top:24px;" class="card">
                    <div class="card-header" style="background-color:#fce8ed">

                        <div class="text-center "><h1>login</h1> </div>
                    </div>
                    <div class="card-body">

                        <div>
                            @Html.AntiForgeryToken()
                            <div>

                            </div>
                            <div style="border-radius:8px;border-color:#921c37">
                                @Html.TextBoxFor(m => m.strEmail, new { @class = "form-control txtbox", @placeholder = "Email" })
                            </div>
                            <div style="padding-top:20px;"></div>
                            <div>

                            </div>
                            <div style="border-radius:8px;border-color:#921c37">
                                @Html.PasswordFor(m => m.strPassword, new { @class = "form-control txtbox", @placeholder = "Password" })
                            </div>
                        </div>

                    </div>
                    <div style="text-align:center;margin-bottom:16px">



                        <div style="padding-top:20px;">
                            <input id="Button1" type="submit" value="Login" style=" width:180px;text-align:center;  box-shadow:0 4px 8px rgba(1,1,0.2,0.2); background-color:#921c37;padding:8px;border-radius:18px;color:white" />


                        </div>
                    </div>

                    <div style="margin:24px">
                        <div class="row">
                            <div class="col-6">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="defaultUnchecked">
                                    <label class="custom-control-label" for="defaultUnchecked">Remember Me</label>
                                </div>
                            </div>
                            <div class="col-6">
                                <a asp-action="" asp-controller="">  Forgot Password</a>

                            </div>
                        </div>
                        <p></p>
                        <div>
                            Don't have an account? <a asp-action="Create" asp-controller="c_Users"> Sign Up</a>
                        </div>
                    </div>



                </div>
            }
        </div>

        <div class=" col-lg-4 col-md-4 col-sm-4  "></div>
    </div>

</div>

<!-- Button trigger modal -->